[build]
builder = "nixpacks"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar target/tracker-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
JAVA_HOME = "/nix/var/nix/profiles/default"
